services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - "1086:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_is_secret
      MYSQL_DATABASE: farnost_db
      MYSQL_USER: nette_user
      MYSQL_PASSWORD: user_password_is_secret
    volumes:
      - farnost_db_data:/var/lib/mysql

volumes:
  farnost_db_data: